# According to
# https://docs.travis-ci.com/user/languages/minimal-and-generic/#generic, the
# generic language includes Go.
language: generic
os: osx

cache:
  directories:
    - cgotorch/libtorch

before_install:
  - brew update
  - brew install wget clang

script:
  - (cd cgotorch; make)
  - go run 01-backward.go
