language: generic
dist: bionic

cache:
  directories:
    - cgotorch/libtorch

before_install:
  - sudo apt-get update
  - sudo apt-get install -y make wget clang

script:
  - (cd cgotorch; make)
  - go run 01-backward.go
